name: Makefile CI

on:
  push:
    paths-ignore:
      - "web/**"
  pull_request:
    paths-ignore:
      - "web/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y nasm

    - name: Makefile
      run: make -C src
